### ISSUE TITLE
Multiple Streams using AioQuic

### ISSUE THREAD

**Issue by devkdas** [etkaar/etkaar#1]
hai ,

It is not an issue.
one small quick query

@etkaar 
Could you please confirm were you able to create multiple streams in a single connection using the AIOQUIC code .

Sorry for raising an issue to ask this query.

Looking forward for your reply

Thank you.

**Comment by etkaar** [comment]
Hi [Karthikdasari0423](https://github.com/Karthikdasari0423)!

I did not use it then, what I did, is to write my own protocol:
https://github.com/etkaar/Neutrino

**Comment by devkdas** [comment]
Hai @etkaar 

Thank you for replying back and 

Providing info about your protocol

Thank you
@Karthikdasari0423
